# Generated by Django 5.0.4 on 2024-04-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=255)),
            ],
        ),
    ]
