# Generated by Django 5.0.4 on 2024-04-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_newsletter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
