# Generated by Django 5.0.4 on 2024-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contactmessage_date_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date_created'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=255, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Subject'),
        ),
    ]
