# Generated by Django 5.0.4 on 2024-04-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_wo_discount_alter_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_wo_discount',
        ),
    ]
