# Generated by Django 5.0.4 on 2024-04-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price_wo_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_selling',
            field=models.BooleanField(default=False),
        ),
    ]
