# Generated by Django 5.0.4 on 2024-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_top_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='default_product_img.jpg', upload_to='products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.TextField(blank=True, max_length=500, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.FloatField(choices=[(1.18, 'A: 18%'), (1.05, 'Б: 5%'), (1.1, 'В: 10%'), (1.0, 'Г: 0%')], default=1.0, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_selling',
            field=models.BooleanField(default=False, verbose_name='top_selling'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='total_price'),
        ),
    ]
