# Generated by Django 5.0.4 on 2024-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_created_date_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='products', verbose_name='Image'),
        ),
    ]
