# Generated by Django 5.0.4 on 2024-04-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_alter_brand_options'),
        ('categories', '0011_alter_category_options'),
        ('products', '0010_alter_productgallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'ProductGallery', 'verbose_name_plural': 'ProductGalleries'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='categories.category'),
        ),
    ]
