# Generated by Django 5.0.4 on 2024-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='category_default_img.jpg', upload_to='brand_photos', verbose_name='image'),
        ),
    ]
