# Generated by Django 5.0.4 on 2024-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='category_default_img.jpg', upload_to='brand_photos', verbose_name='Image'),
        ),
    ]
