# Generated by Django 5.0.4 on 2024-04-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_brand_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
