# Generated by Django 5.0.4 on 2024-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_default_image.jpg', upload_to='category_photos'),
        ),
    ]
