# Generated by Django 5.0.4 on 2024-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_category_image.jpg', upload_to='category_photos', verbose_name='image'),
        ),
    ]
