# Generated by Django 5.0.4 on 2024-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_category_image.jpg', upload_to='category_photos', verbose_name='Image'),
        ),
    ]
