# Generated by Django 5.0.4 on 2024-04-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_maincategory_remove_category_parent_subcategory'),
        ('products', '0013_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
